export const games = [
  {
    id: "tictactoe",
    title: "Tic Tac Toe",
    slug: "tic-tac-toe",
    icon: "tictactoe",
    category: "Board",
    level: "Mudah",
    author: "Game Arena",
    age: "baru saja",
    views: 284,
    likes: 81,
    modes: ["WEB-VIEW"],
    tags: ["Board", "Strategi", "Casual"],
    description: "Duel 3x3 yang cepat untuk dua pemain. Menang dengan tiga simbol sejajar.",
    createdAt: "2026-10-01"
  },
  {
    id: "snake",
    title: "Snake Classic",
    slug: "snake-classic",
    icon: "snake",
    category: "Arcade",
    level: "Sedang",
    author: "Arcade Lab",
    age: "1 hari lalu",
    views: 431,
    likes: 112,
    modes: ["WEB-VIEW", "IN-CHAT"],
    tags: ["Arcade", "Retro"],
    description: "Ambil makanan, panjangkan badan, dan tahan selama mungkin tanpa menabrak.",
    createdAt: "2026-09-30"
  },
  {
    id: "memory",
    title: "Memory Match",
    slug: "memory-match",
    icon: "memory",
    category: "Puzzle",
    level: "Mudah",
    author: "Game Arena",
    age: "2 hari lalu",
    views: 198,
    likes: 64,
    modes: ["WEB-VIEW"],
    tags: ["Puzzle", "Memory"],
    description: "Buka kartu, ingat posisinya, lalu cari pasangan dengan gerakan paling sedikit.",
    createdAt: "2026-09-29"
  },
  {
    id: "guess",
    title: "Tebak Angka",
    slug: "tebak-angka",
    icon: "guess",
    category: "Casual",
    level: "Mudah",
    author: "Game Arena",
    age: "3 hari lalu",
    views: 147,
    likes: 39,
    modes: ["IN-CHAT"],
    tags: ["Casual", "Quick"],
    description: "Cari angka rahasia dari 1 sampai 100 dengan petunjuk naik atau turun.",
    createdAt: "2026-09-28"
  },
  {
    id: "rps",
    title: "Batu Gunting Kertas",
    slug: "batu-gunting-kertas",
    icon: "rps",
    category: "Casual",
    level: "Mudah",
    author: "Classic Pack",
    age: "4 hari lalu",
    views: 226,
    likes: 73,
    modes: ["WEB-VIEW", "IN-CHAT"],
    tags: ["Casual", "Quick"],
    description: "Satu ronde cepat melawan komputer. Cocok buat main singkat.",
    createdAt: "2026-09-27"
  },
  {
    id: "whack",
    title: "Whack Target",
    slug: "whack-target",
    icon: "whack",
    category: "Action",
    level: "Sedang",
    author: "Arcade Lab",
    age: "5 hari lalu",
    views: 312,
    likes: 88,
    modes: ["WEB-VIEW"],
    tags: ["Action", "Refleks"],
    description: "Pukul target yang muncul secara acak sebelum timer habis.",
    createdAt: "2026-09-26"
  },
  {
    id: "twenty48",
    title: "2048 Mini",
    slug: "2048-mini",
    icon: "twenty48",
    category: "Puzzle",
    level: "Sedang",
    author: "Puzzle Shelf",
    age: "6 hari lalu",
    views: 389,
    likes: 105,
    modes: ["WEB-VIEW"],
    tags: ["Puzzle", "Number"],
    description: "Geser angka, gabungkan tile yang sama, dan kejar skor tertinggi.",
    createdAt: "2026-09-25"
  },
  {
    id: "mines",
    title: "Minesweeper Lite",
    slug: "minesweeper-lite",
    icon: "mines",
    category: "Puzzle",
    level: "Sedang",
    author: "Classic Pack",
    age: "7 hari lalu",
    views: 174,
    likes: 52,
    modes: ["WEB-VIEW"],
    tags: ["Puzzle", "Logika"],
    description: "Buka semua petak aman dengan membaca angka di sekitar ranjau.",
    createdAt: "2026-09-24"
  },
  {
    id: "quiz",
    title: "Quiz Cepat",
    slug: "quiz-cepat",
    icon: "quiz",
    category: "Trivia",
    level: "Mudah",
    author: "Game Arena",
    age: "8 hari lalu",
    views: 133,
    likes: 41,
    modes: ["IN-CHAT"],
    tags: ["Trivia", "Quick"],
    description: "Jawab lima pertanyaan singkat dan lihat skor akhir kamu.",
    createdAt: "2026-09-23"
  },
  {
    id: "scramble",
    title: "Susun Kata",
    slug: "susun-kata",
    icon: "scramble",
    category: "Word",
    level: "Mudah",
    author: "Puzzle Shelf",
    age: "9 hari lalu",
    views: 119,
    likes: 37,
    modes: ["WEB-VIEW"],
    tags: ["Word", "Puzzle"],
    description: "Tebak kata asli dari huruf yang sudah diacak.",
    createdAt: "2026-09-22"
  },
  {
    id: "reaction",
    title: "Tes Refleks",
    slug: "tes-refleks",
    icon: "reaction",
    category: "Action",
    level: "Mudah",
    author: "Arcade Lab",
    age: "10 hari lalu",
    views: 267,
    likes: 96,
    modes: ["WEB-VIEW"],
    tags: ["Action", "Refleks"],
    description: "Tunggu sinyal hijau lalu tekan secepat mungkin untuk mengukur refleks.",
    createdAt: "2026-09-21"
  }
];
